version: "3.7"

services:
  producer:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /producer
    volumes:
      - ./producer/:/producer

  consumer:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
        - 3001:5000
    working_dir: /consumer
    volumes:
      - ./consumer/:/consumer

  queue:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 15672:15672
        - 5672:5672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    labels:
        NAME: rabbitmq1
  
  frontend:
    image: node:12-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 8080:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    

 